version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    volumes:
      - .:/code
    env_file:
      - docker/local/python.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    env_file:
      - docker/local/python.env
